insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (1, 'Trevena, Inc.', 16, '12:40', '17:20');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (2, 'Guaranty Federal Bancshares, Inc.', 8, '13:47', '14:03');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (3, 'Central Garden & Pet Company', 13, '16:01', '16:47');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (4, 'Sensus Healthcare, Inc.', 20, '14:41', '18:20');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (5, 'Cavium, Inc.', 2, '7:10', '16:57');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (6, 'Kayne Anderson Acquisition Corp.', 36, '15:25', '14:17');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (7, 'First Trust Total US Market AlphaDEX ETF', 28, '13:56', '15:35');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (8, 'Melco Resorts & Entertainment Limited', 25, '12:56', '13:52');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (9, 'Shineco, Inc.', 9, '9:13', '12:50');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (10, 'Callon Petroleum Company', 29, '12:19', '16:28');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (11, 'Five Below, Inc.', 6, '9:31', '12:29');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (12, 'Nuveen California Municipal Value Fund, Inc.', 7, '11:30', '11:19');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (13, 'Nuveen Mortgage Opportunity Term Fund', 23, '7:04', '15:08');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (14, 'Catalyst Biosciences, Inc. ', 47, '14:18', '15:05');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (15, 'iPath US Treasury 2-year Bear ETN', 46, '11:16', '8:13');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (16, 'Steel Partners Holdings LP', 23, '14:09', '11:40');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (17, 'ClearBridge Energy MLP Opportunity Fund Inc.', 15, '15:23', '14:05');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (18, 'Eaton Vance Tax-Managed Global Diversified Equity Income Fund', 41, '8:25', '17:47');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (19, 'Alamo Group, Inc.', 28, '9:57', '13:54');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (20, 'Avnet, Inc.', 20, '6:56', '15:14');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (21, 'Fresh Del Monte Produce, Inc.', 15, '7:04', '13:37');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (22, 'Gabelli Dividend', 20, '12:12', '11:32');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (23, 'Kaiser Aluminum Corporation', 35, '16:02', '14:16');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (24, 'Entegra Financial Corp.', 14, '7:55', '15:52');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (25, 'Wayside Technology Group, Inc.', 2, '7:19', '17:58');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (26, 'Dicerna Pharmaceuticals, Inc.', 17, '11:32', '15:00');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (27, 'Cleveland BioLabs, Inc.', 42, '8:48', '16:52');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (28, 'Camtek Ltd.', 14, '7:24', '14:01');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (29, 'Sequans Communications S.A.', 4, '7:13', '17:16');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (30, 'NeoGenomics, Inc.', 13, '9:59', '17:11');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (31, 'KCAP Financial, Inc.', 38, '9:29', '13:06');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (32, 'Nuveen Diversified Dividend and Income Fund', 35, '7:13', '14:44');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (33, 'Republic Services, Inc.', 42, '13:47', '11:16');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (34, 'Yahoo! Inc.', 42, '9:42', '15:14');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (35, 'PPlus Trust', 42, '11:47', '8:26');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (36, 'Colony Starwood Homes', 25, '12:06', '11:52');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (37, 'Miller Industries, Inc.', 38, '16:44', '14:59');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (38, 'Tronox Limited', 36, '15:17', '12:20');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (39, 'Westport Fuel Systems Inc', 42, '14:32', '12:25');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (40, 'Service Corporation International', 45, '10:19', '13:52');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (41, 'Royal Bank Scotland plc (The)', 12, '12:16', '11:26');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (42, 'Alamos Gold Inc.', 33, '15:04', '9:15');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (43, 'Catalyst Biosciences, Inc. ', 4, '7:49', '13:25');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (44, 'Equity Residential', 30, '15:01', '15:53');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (45, 'Lindsay Corporation', 33, '10:59', '17:07');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (46, 'Beneficial Bancorp, Inc.', 35, '12:16', '8:14');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (47, 'Century Aluminum Company', 9, '14:00', '16:06');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (48, 'Newtek Business Services Corp.', 20, '8:37', '17:49');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (49, 'La-Z-Boy Incorporated', 7, '10:35', '9:37');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (50, 'Westport Fuel Systems Inc', 16, '9:09', '12:52');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (51, 'Five Point Holdings, LLC', 28, '7:30', '18:17');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (52, 'Wilhelmina International, Inc.', 24, '8:56', '14:37');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (53, 'First Trust NASDAQ ABA Community Bank Index Fund', 9, '14:59', '8:29');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (54, 'Parker Drilling Company', 20, '15:43', '16:18');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (55, 'First Trust NASDAQ Cybersecurity ETF', 41, '13:17', '11:33');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (56, 'Guggenheim Credit Allocation Fund', 10, '8:36', '16:51');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (57, 'Spire Inc.', 34, '14:11', '16:16');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (58, 'Barrick Gold Corporation', 45, '9:00', '9:05');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (59, 'Net Element, Inc.', 15, '7:11', '8:58');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (60, 'Delaware Investments Dividend & Income Fund, Inc.', 29, '7:41', '14:04');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (61, 'Heska Corporation', 10, '13:28', '14:01');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (62, 'Nexstar Media Group, Inc.', 7, '15:00', '14:59');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (63, 'Enel Generacion Chile S.A.', 31, '8:05', '16:16');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (64, 'B.O.S. Better Online Solutions', 10, '16:09', '18:26');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (65, 'Kinross Gold Corporation', 44, '11:32', '18:10');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (66, 'TearLab Corporation', 4, '7:23', '14:33');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (67, 'AstroNova, Inc.', 10, '12:51', '12:25');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (68, 'Fitbit, Inc.', 41, '13:37', '13:36');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (69, 'Kennedy-Wilson Holdings Inc.', 4, '14:12', '16:29');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (70, 'Allison Transmission Holdings, Inc.', 34, '16:18', '11:29');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (71, 'Anadarko Petroleum Corporation', 4, '12:57', '10:07');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (72, 'JMU Limited', 7, '10:09', '11:53');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (73, 'Synthetic Fixed-Income Securities, Inc.', 50, '9:39', '8:25');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (74, 'Patrick Industries, Inc.', 33, '12:22', '16:06');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (75, 'Monogram Residential Trust, Inc.', 40, '11:43', '14:30');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (76, 'VelocityShares 3x Inverse Silver ETN', 47, '9:52', '14:29');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (77, 'AGCO Corporation', 48, '11:05', '8:25');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (78, 'NextEra Energy Partners, LP', 47, '14:17', '18:09');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (79, 'DLH Holdings Corp.', 26, '15:09', '16:59');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (80, 'Liberty Expedia Holdings, Inc.', 31, '15:31', '13:40');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (81, 'Lindblad Expeditions Holdings Inc. ', 16, '12:21', '15:15');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (82, 'REX American Resources Corporation', 11, '11:12', '15:42');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (83, 'Meridian Waste Solutions, Inc', 50, '13:20', '13:06');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (84, 'Korea Fund, Inc. (The)', 20, '10:32', '10:37');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (85, 'Weis Markets, Inc.', 16, '7:19', '9:21');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (86, 'Associated Banc-Corp', 47, '10:52', '13:43');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (87, 'Cardiovascular Systems, Inc.', 25, '13:47', '15:21');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (88, 'Seanergy Maritime Holdings Corp', 7, '11:48', '12:30');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (89, 'ChemoCentryx, Inc.', 20, '13:42', '14:24');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (90, 'First Trust Nasdaq Transportation ETF', 30, '14:48', '17:57');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (91, 'Nuveen High Income December 2019 Target Term Fund', 42, '12:05', '10:13');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (92, 'Sapiens International Corporation N.V.', 35, '11:57', '9:02');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (93, 'Rogers Communication, Inc.', 10, '11:36', '17:18');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (94, 'Grupo Aeroportuario Del Pacifico, S.A. de C.V.', 1, '10:15', '15:53');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (95, 'Nuveen Quality Municipal Income Fund', 12, '8:09', '12:52');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (96, 'Life Storage, Inc.', 50, '9:58', '12:09');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (97, 'Universal Electronics Inc.', 16, '9:17', '11:33');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (98, 'Rice Midstream Partners LP', 25, '12:59', '13:03');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (99, 'Boston Private Financial Holdings, Inc.', 29, '6:52', '9:11');
insert into Class (ClassID, Class_Name, TeacherID, Start_Time, End_Time) values (100, 'Dawson Geophysical Company', 43, '7:44', '16:02');