--ADD TEACHER DATA
DECLARE @numTEACHER INT;
SET @numTEACHER=0;
WHILE (@numTEACHER<100)
BEGIN
DECLARE @StartDateTEACHER DATE;
DECLARE @EndDateTEACHER  DATE;
DECLARE @birthdayTEACHER DATE;
SET @StartDateTEACHER = '01/01/60';
SET @EndDateTEACHER   = '12/31/1995';
SET @birthdayTEACHER = DATEADD(DAY, RAND(CHECKSUM(NEWID()))*(1+DATEDIFF(DAY, @StartDateTEACHER, @EndDateTEACHER)),@StartDateTEACHER) ;
DECLARE @stayyear INT;
SET @stayyear = FLOOR(RAND()*(2010-1990)+1990);
INSERT INTO teacher (TEACHER_ID,TEACHER_NAME,BIRTHDAY_TEACHER,EMAIL_TEACHER,PHONENUMBER_TEACHER,STARTYEAR) 
VALUES (@numTEACHER,CONCAT('TEACHER_NAME_',@numTEACHER),@birthdayTEACHER,CONCAT('EMAIL_TEACHER_',@numTEACHER),CONCAT('PHONE_TEACHER_',@numTEACHER),@stayyear);
SET @numTEACHER = @numTEACHER+1;
END
--------------------------------------------------
--ADD CLASS DATA
DECLARE @numCLASS INT;
SET @numCLASS =0;
WHILE (@numCLASS<50) 
BEGIN
DECLARE @StartDateCLASS DATE;
DECLARE @EndDateCLASS  DATE;
DECLARE @starttime DATE;
DECLARE @endtime DATE;
SET @StartDateCLASS = '01/01/2016';
SET @EndDateCLASS   = '12/31/2021';
 SET @starttime = DATEADD(DAY, RAND(CHECKSUM(NEWID()))*(1+DATEDIFF(DAY, @StartDateCLASS, @EndDateCLASS)),@StartDateCLASS) ;
 set @endtime = DATEADD(MONTH, 6, @starttime) ;
DECLARE @teacher_id INT;
SET @teacher_id = FLOOR(100*RAND());
INSERT INTO class (CLASS_ID,CLASS_NAME,TEACHER_ID,START_TIME,END_TIME) 
VALUES (@numCLASS,CONCAT('CLASS_NAME_',@numCLASS),@teacher_id,@starttime,@endtime);
SET @numCLASS = @numCLASS+1;
END
----------------------------------------------
--ADD STUDENT DATA
DECLARE @numSTUDENT INT;
SET @numSTUDENT=0;
WHILE (@numSTUDENT <1000) 
BEGIN
DECLARE @gen VARCHAR(45);
SET @gen =CASE FLOOR(RAND()*2) WHEN 1 THEN  'MALE' ELSE 'FEMALE' END;
DECLARE @StartDate DATE;
DECLARE @EndDate  DATE;
DECLARE @birthday DATE;
SET @StartDate = '01/01/60';
SET @EndDate   = '12/31/1995';
 SET @birthday = DATEADD(DAY, RAND(CHECKSUM(NEWID()))*(1+DATEDIFF(DAY, @StartDate, @EndDate)),@StartDate) ;
DECLARE @score INT;
SET @score = FLOOR(RAND()*10);
DECLARE @class_id INT;
SET @class_id = FLOOR(RAND()*50);
INSERT INTO student (STUDENT_ID,STUDENT_NAME,GENDER,BIRTHDAY_STUDENT,EMAIL_STUDENT,PHONENUMBER_STUDENT,SCORE,CLASS_ID)
VALUES(@numSTUDENT,CONCAT('STUDENT_NAME_',@numSTUDENT),@gen, @birthday,CONCAT('EMAIL_STUDENT_',@numSTUDENT),CONCAT('PHONE_STUDENT_',@numSTUDENT),@score,@class_id);
SET @numSTUDENT= @numSTUDENT+1;
END
