CREATE DATABASE STUDENTMANAGEMENT
----------------------------------------------
CREATE TABLE teacher(
TEACHER_ID INT NOT NULL PRIMARY KEY,
TEACHER_NAME VARCHAR(256),
BIRTHDAY_TEACHER DATE,
EMAIL_TEACHER VARCHAR(256),
PHONENUMBER_TEACHER VARCHAR(256),
STARTYEAR INT,
);
-----------------------------------------------
CREATE TABLE class (
CLASS_ID INT NOT NULL PRIMARY KEY,
CLASS_NAME VARCHAR(256) NOT NULL,
TEACHER_ID INT NOT NULL ,
START_TIME DATE,
END_TIME DATE,
FOREIGN KEY(TEACHER_ID) REFERENCES teacher(TEACHER_ID),
); 
-------------------------------------------------
CREATE TABLE student (
STUDENT_ID INT NOT NULL PRIMARY KEY,
STUDENT_NAME VARCHAR(256)NOT NULL,
GENDER VARCHAR(256),
BIRTHDAY_STUDENT DATE,
EMAIL_STUDENT VARCHAR(256),
PHONENUMBER_STUDENT VARCHAR(256),
SCORE FLOAT NOT NULL,
CLASS_ID INT NOT NULL,
FOREIGN KEY(CLASS_ID) REFERENCES class(CLASS_ID),
);

